### ISSUE TITLE
Source code available

### ISSUE THREAD

**Issue by zxjinn** [Sfinx/nest#1]
Hey, this looks really neat- but I don't see any source code, only a binary. 

I was curious if you could make the source available in this repo? Thanks!

**Comment by Sfinx** [comment]
The source code available under commercial licenses only, contact privately with your problem description for more info. Commercial app supports ring & nest devices with video & two way audio. So the custom SIP/RTSP gateways available for more sophisticated integration (Crestron  for ex.).
